/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "anomaly_metadata.h"
#include "tflite-model/tflite_learn_950386_5_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_950386_1[] = { "motion_attack", "motion_circle", "motion_poke" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_950386_4_axes[] = { 0, 1, 2 };
const uint32_t ei_dsp_config_950386_4_axes_size = 3;
ei_dsp_config_spectral_analysis_t ei_dsp_config_950386_4 = {
    4, // uint32_t blockId
    4, // int implementationVersion
    3, // int length of axes
    0.0078431372549f, // float scale-axes
    1, // int input-decimation-ratio
    "low", // select filter-type
    7.0f, // float filter-cutoff
    2, // int filter-order
    "FFT", // select analysis-type
    128, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_950386_4[69] = { 0.1423765053237249, -2.139703828132224, 6.95047509445744, 4.861345824115501, 26.66258051209077, -0.9310315817101017, -0.6656572164194042, -1.2076634789755445, -1.4314435623690696, -1.557083725212571, -1.6245537354855355, -1.7238411433949976, -1.8670190976473515, -1.8840314763820243, -1.8905466938305475, -1.9367882304774497, -2.1027907266884385, -2.0855209485801285, -2.0559638232171893, -2.068785340131404, -2.20407129480748, -2.227001705485021, -2.2180845032712977, 0.17294235753720413, -0.17823971814115744, 2.479510322156365, 3.1474171887657687, 11.16927763389681, -1.2903357934736774, -1.1680334583372773, -1.1290846113451498, -0.963242459754816, -0.973910523610253, -1.1028841252854926, -1.1141841826075782, -1.1686804771781685, -1.2581005455377345, -1.373684491924867, -1.4107207080166422, -1.4726793380204088, -1.4825709334356274, -1.5623012384575212, -1.6650447104880233, -1.726811067255322, -1.8327951357216539, -1.9201070372470634, 0.18275728770988978, -0.4615020064181202, 2.2858863216798, 3.2608394958452136, 11.766756583430723, -1.238429547967352, -1.0458933519337603, -1.0395441492776833, -0.8812905403828334, -0.8557227785934233, -0.9889749546268422, -1.146268318256061, -1.1967553249700276, -1.216864630968155, -1.3661384306594222, -1.4297178636094134, -1.4561026891868913, -1.4822151247628466, -1.5688169100480471, -1.6641567756752214, -1.7468735801433035, -1.8413806881359918, -1.9430194184154213 };
const float ei_dn_standard_scaler_scale_950386_4[69] = { 20.92007182866315, 0.7279278937212992, 0.09693617151933165, 0.8456640802829344, 0.09078042795474059, 1.3658689435705371, 1.7595700176808782, 1.87554674636886, 1.9108671248850595, 2.0495430678879165, 2.103858023321389, 2.3165969129279773, 2.4477082738258447, 2.604096854639561, 2.6735746356634422, 2.922616447055211, 2.664586549752848, 2.691574882870968, 2.758679349391119, 2.977209122266192, 2.987892894299322, 3.0265318518073365, 2.975877082559572, 22.01296106815898, 0.9181147811613418, 0.16689481013842172, 1.033867162775242, 0.12452838401678501, 1.7266329492763874, 1.779061055284595, 1.766179793196455, 1.611870040278909, 1.657036238659207, 1.9764579160369182, 2.392663734641137, 2.086431307527529, 2.2153409599383984, 2.4178050889568903, 2.553805445617695, 2.3692128349969286, 2.5084313955323116, 2.3994000075581576, 2.1229476134747465, 1.9722539566645947, 1.8983140347017475, 1.9908670322092081, 20.958055396005303, 0.9588167649012244, 0.17754370849094153, 1.1734850336274907, 0.14477187071788755, 1.8906198024966963, 1.7485217276902578, 1.7183422687798973, 1.6917005174195356, 1.7981427598273385, 2.138262263831039, 2.0877678970047824, 2.126118556087627, 2.111259428465619, 2.1904394255889983, 2.3271934441494406, 2.29924858477704, 2.2840563108491727, 2.249824569421935, 2.141948313405282, 2.112987062079397, 1.9743128191568216, 1.9843496842801067 };
const float ei_dn_standard_scaler_var_950386_4[69] = { 0.002284933985633977, 1.887223243733996, 106.42122980990553, 1.398312472666564, 121.34322926719258, 0.5360211661563681, 0.3229883766107536, 0.2842786300764063, 0.2738665699349063, 0.2380597112470083, 0.22592648361296558, 0.18633698040419422, 0.16690935861144404, 0.14746390626526565, 0.13989924644508162, 0.11707289345835492, 0.14084464429560015, 0.13803431556356702, 0.13140066169269968, 0.11281875894036943, 0.11201339207987006, 0.10917155650156991, 0.11291977971225116, 0.0020636833915600164, 1.186331443038303, 35.901644019717956, 0.9355575688306719, 64.4856816981467, 0.33542849332619806, 0.3159499524709963, 0.3205753880029259, 0.3848929476851968, 0.36419668404494576, 0.25599109436948003, 0.17467737861349758, 0.22971630306783244, 0.20375995935095326, 0.1710635282662401, 0.15332902801416765, 0.17815246939700524, 0.15892621651602895, 0.17369794813530007, 0.22188167972118503, 0.2570835734782769, 0.27750057210047646, 0.2522989772994774, 0.0022766592392501226, 1.087749173245164, 31.724108448683786, 0.7261810135935929, 47.71244006019434, 0.2797638495089071, 0.3270829705055276, 0.3386730613651479, 0.34942424520702225, 0.30927987605731444, 0.21871474207314345, 0.229422268360727, 0.22122033427751492, 0.2243452071852751, 0.20841909443972179, 0.1846439279591748, 0.18915949430706314, 0.19168423082693475, 0.19756167042589085, 0.21796262336582195, 0.2239784961176989, 0.25654766676864943, 0.25395898764154295 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_950386_4 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_950386_4,
    .mean_data_len = 69,
    .scale_data = (float *)ei_dn_standard_scaler_scale_950386_4,
    .scale_data_len = 69,
    .var_data = (float *)ei_dn_standard_scaler_var_950386_4,
    .var_data_len = 69
};
ei_data_normalization_t ei_data_normalization_config_950386_4 = {
    (void *) &ei_data_normalization_standard_scaler_config_950386_4, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_950386_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_950386_1[ei_dsp_blocks_950386_1_size] = {
    { // DSP block 4
        4,
        69, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_950386_4, // pointer to config struct
        ei_dsp_config_950386_4_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_950386_4_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_950386_4, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_950386_5 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_950386_5_init,
    .model_invoke = &tflite_learn_950386_5_invoke,
    .model_reset = &tflite_learn_950386_5_reset,
    .model_input = &tflite_learn_950386_5_input,
    .model_output = &tflite_learn_950386_5_output,
};

const uint8_t ei_output_tensors_indices_950386_5[1] = { 0 };
const uint8_t ei_output_tensors_size_950386_5 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_950386_5 = {
    .implementation_version = 1,
    .block_id = 5,
    .output_tensors_indices = ei_output_tensors_indices_950386_5,
    .output_tensors_size = ei_output_tensors_size_950386_5,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_950386_5,
    .dequantize_output = 0,
};

const ei_learning_block_config_anomaly_kmeans_t ei_learning_block_config_950386_6 = {
    .implementation_version = 1,
    .block_id = 6,
    .anom_axis = ei_classifier_anom_axes_950386_6,
    .anom_axes_size = 4,
    .anom_clusters = ei_classifier_anom_clusters_950386_6,
    .anom_cluster_count = 128,
    .anom_scale = ei_classifier_anom_scale_950386_6,
    .anom_mean = ei_classifier_anom_mean_950386_6,
};

const uint8_t ei_learning_blocks_950386_1_size = 2;
const uint32_t ei_learning_block_950386_5_inputs[1] = { 4 };
const uint8_t ei_learning_block_950386_5_inputs_size = 1;
const uint32_t ei_learning_block_950386_6_inputs[1] = { 4 };
const uint8_t ei_learning_block_950386_6_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_950386_1[ei_learning_blocks_950386_1_size] = {
    {
        5,
        &run_nn_inference,
        (void*)&ei_learning_block_config_950386_5,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_950386_5_inputs,
        ei_learning_block_950386_5_inputs_size,
    },
    {
        6,
        &run_kmeans_anomaly,
        (void*)&ei_learning_block_config_950386_6,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_950386_6_inputs,
        ei_learning_block_950386_6_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_950386_5 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_950386_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_950386_1[ei_postprocessing_blocks_950386_1_size] = {
    {
        .block_id = 5,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_950386_5,
        .input_block_id = 5
    },
};

const uint8_t freeform_outputs_950386_1_size = 0;

uint32_t *freeform_outputs_950386_1 = nullptr;

const ei_impulse_t impulse_950386_1 = {
    .project_id = 950386,
    .project_owner = "nbures",
    .project_name = "motion",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 1,

    .nn_input_frame_size = 69,
    .raw_sample_count = 100,
    .raw_samples_per_frame = 3,
    .dsp_input_frame_size = 100 * 3,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 20,
    .frequency = 50,

    .dsp_blocks_size = ei_dsp_blocks_950386_1_size,
    .dsp_blocks = ei_dsp_blocks_950386_1,

    .learning_blocks_size = ei_learning_blocks_950386_1_size,
    .learning_blocks = ei_learning_blocks_950386_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_950386_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_950386_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "x-axis acceleration + y-axis acceleration + z-axis acceleration",
    .slice_size = (100/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_KMEANS,
    .label_count = 3,
    .categories = ei_classifier_inferencing_categories_950386_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_950386_1_size,
    .freeform_outputs = freeform_outputs_950386_1
};

ei_impulse_handle_t impulse_handle_950386_1 = ei_impulse_handle_t( &impulse_950386_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_950386_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_950386_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_950386_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_950386_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
